import React from 'react'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <section className="container mx-auto grid grid-cols-5 gap-16 2xl:my-16 my-0 bg-orange-100 pr-16 shadow-2xl drop-shadow-2xl">
          <aside className="col-span-1 bg-orange-950 text-white">
            <ul>
              <li>
                <a href="/" className="p-4 block bg-orange-700 border-b">
                  Home
                </a>
              </li>
              <li>
                <a
                  href="/tasks"
                  className="p-4 block hover:bg-orange-700 border-b"
                >
                  Tasks
                </a>
              </li>
              <li>
                <a
                  href="/assignable"
                  className="p-4 block hover:bg-orange-700 border-b"
                >
                  Assignable
                </a>
              </li>
              <li>
                <a
                  href="/assignment"
                  className="p-4 block hover:bg-orange-700 border-b"
                >
                  Assignment
                </a>
              </li>
            </ul>
          </aside>
          {children}
        </section>
      </body>
    </html>
  )
}
